import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import { useEffect, useState } from "react"
import { useParams, Link } from "react-router-dom"
import axios from "axios"
import AdminLayout from "../layouts/AdminLayout"

function AdminOrderDetails() {

    const { id } = useParams()

    const [order, setOrder] = useState(null)

    useEffect(() => {

        axios
            .get(`http://localhost:5000/admin/orders/${id}`)
            .then((res) => {

                setOrder(res.data)

            })
            .catch((err) => {

                console.log(err)

            })

    }, [id])

    const downloadInvoice = () => {

        if (!order) return

        const doc = new jsPDF()

        const grandTotal = order.items.reduce(

            (sum, item) => sum + item.price * item.quantity,

            0

        )

        // ==========================
        // HEADER
        // ==========================

        doc.setFont("helvetica", "bold")
        doc.setFontSize(24)

        doc.text("URBANSTORE", 20, 20)

        doc.setFontSize(18)

        doc.text("INVOICE", 155, 20)

        doc.line(20, 28, 190, 28)

        // ==========================
        // INVOICE INFO
        // ==========================

        doc.setFont("helvetica", "normal")
        doc.setFontSize(11)

        doc.text(
            `Invoice No : INV-${order._id.slice(-6).toUpperCase()}`,
            20,
            40
        )

        doc.text(
            `Order ID : #${order._id.slice(-6).toUpperCase()}`,
            20,
            48
        )

        doc.text(
            `Date : ${new Date(order.createdAt).toLocaleDateString("en-IN")}`,
            20,
            56
        )

        // ==========================
        // BILL TO
        // ==========================

        doc.setFillColor(245, 245, 245)

        doc.roundedRect(
            20,
            66,
            170,
            42,
            3,
            3,
            "F"
        )

        doc.setFont("helvetica", "bold")
        doc.setFontSize(13)

        doc.text("BILL TO", 25, 76)

        doc.setFont("helvetica", "normal")
        doc.setFontSize(11)

        doc.text(order.customerName, 25, 86)
        doc.text(order.email, 25, 93)
        doc.text(order.phone, 25, 100)
        doc.text(order.address, 25, 107)

        // ==========================
        // PRODUCT TABLE
        // ==========================

        autoTable(doc, {

            startY: 120,

            head: [[
                "Product",
                "Size",
                "Qty",
                "Price",
                "Total"
            ]],

            body: order.items.map(item => ([

                item.name,

                item.size || "-",

                item.quantity,

                `₹${item.price}`,

                `₹${item.price * item.quantity}`

            ])),

            theme: "grid",

            headStyles: {

                fillColor: [31, 41, 55],

                textColor: 255,

                fontStyle: "bold"

            },

            alternateRowStyles: {

                fillColor: [245, 245, 245]

            },

            styles: {

                fontSize: 10,

                cellPadding: 4

            }

        })

        const finalY = doc.lastAutoTable.finalY + 15

        doc.setFontSize(12)

        doc.text("Subtotal", 130, finalY)
        doc.text(`₹${grandTotal}`, 170, finalY)

        doc.text("Shipping", 130, finalY + 10)
        doc.text("FREE", 170, finalY + 10)

        doc.setFont("helvetica", "bold")
        doc.setFontSize(14)

        doc.text("Grand Total", 130, finalY + 25)
        doc.text(`₹${grandTotal}`, 170, finalY + 25)

        doc.setFont("helvetica", "normal")
        doc.setFontSize(11)

        doc.text(
            `Payment Status : ${order.status}`,
            20,
            finalY + 15
        )

        doc.text(
            `Order Status : ${order.status}`,
            20,
            finalY + 25
        )

        doc.line(
            20,
            270,
            190,
            270
        )

        doc.setFontSize(10)

        doc.text(
            "Thank you for shopping with UrbanStore!",
            60,
            278
        )

        doc.text(
            "Generated by UrbanStore Admin Dashboard",
            45,
            285
        )

        doc.save(
            `Invoice-${order._id.slice(-6).toUpperCase()}.pdf`
        )

    }

    if (!order) {

        return (

            <AdminLayout>

                <div className="flex justify-center items-center h-[70vh]">

                    <h1 className="text-3xl font-serif">

                        Loading Order...

                    </h1>

                </div>

            </AdminLayout>

        )

    }

    return (

        <AdminLayout>

            {/* Back Button */}

            <div className="flex justify-between items-center mb-8">

                <Link
                    to="/admin/orders"
                    className="text-blue-600 hover:underline"
                >
                    ← Back to Orders
                </Link>

                <div className="flex gap-3">

                    <button
                        onClick={() => window.print()}
                        className="border border-[#D9CFC2] px-5 py-3 rounded-xl hover:bg-black hover:text-white transition"
                    >
                        Print
                    </button>

                    <button
                        onClick={downloadInvoice}
                        className="bg-green-600 text-white px-5 py-3 rounded-xl hover:bg-green-700 transition"
                    >
                        Download Invoice
                    </button>

                </div>

            </div>

            {/* Header */}

            <div className="bg-white rounded-3xl shadow-sm p-8 mb-8">

                <div className="flex justify-between items-center">

                    <div>

                        <p className="uppercase tracking-[3px] text-gray-400 text-sm">

                            Order

                        </p>

                        <h1 className="text-4xl font-serif mt-2">

                            #{order._id.slice(-6).toUpperCase()}

                        </h1>

                        <p className="text-gray-500 mt-2">

                            Invoice No :

                            <span className="font-medium ml-2">

                                INV-{order._id.slice(-6).toUpperCase()}

                            </span>

                        </p>

                        <p className="text-gray-500 mt-3">

                            {new Date(order.createdAt).toLocaleString()}

                        </p>

                    </div>

                    <span
                        className={`px-6 py-3 rounded-full font-medium

                    ${order.status === "Delivered"

                                ? "bg-green-100 text-green-700"

                                : order.status === "Cancelled"

                                    ? "bg-red-100 text-red-600"

                                    : order.status === "Shipped"

                                        ? "bg-blue-100 text-blue-600"

                                        : order.status === "Paid"

                                            ? "bg-emerald-100 text-emerald-700"

                                            : "bg-yellow-100 text-yellow-700"

                            }`}
                    >

                        {order.status}

                    </span>

                </div>

            </div>

            {/* Customer + Payment */}

            <div className="grid lg:grid-cols-2 gap-6">

                <div className="bg-white rounded-3xl shadow-sm p-8">

                    <h2 className="text-2xl font-serif mb-6">

                        Customer Information

                    </h2>

                    <div className="space-y-4">

                        <div>

                            <p className="text-gray-500 text-sm">
                                Name
                            </p>

                            <p className="font-medium">
                                {order.customerName}
                            </p>

                        </div>

                        <div>

                            <p className="text-gray-500 text-sm">
                                Email
                            </p>

                            <p>
                                {order.email}
                            </p>

                        </div>

                        <div>

                            <p className="text-gray-500 text-sm">
                                Phone
                            </p>

                            <p>
                                {order.phone}
                            </p>

                        </div>

                        <div>

                            <p className="text-gray-500 text-sm">
                                Shipping Address
                            </p>

                            <p>
                                {order.address}
                            </p>

                        </div>

                    </div>

                </div>

                <div className="bg-white rounded-3xl shadow-sm p-8">

                    <h2 className="text-2xl font-serif mb-6">

                        Payment Summary

                    </h2>

                    <div className="space-y-4">

                        <div className="flex justify-between">

                            <span>Items</span>

                            <span>

                                {order.items.length}

                            </span>

                        </div>

                        <div className="flex justify-between">

                            <span>Shipping</span>

                            <span>

                                FREE

                            </span>

                        </div>

                        <div className="border-t pt-4 flex justify-between">

                            <span className="font-semibold">

                                Grand Total

                            </span>

                            <span className="text-2xl font-serif">

                                ₹{order.totalAmount}

                            </span>

                        </div>

                    </div>

                </div>
            </div>

            {/* Order Timeline */}

            <div className="bg-white rounded-3xl shadow-sm p-8 mt-8">

                <h2 className="text-2xl font-serif mb-8">
                    Order Timeline
                </h2>

                <div className="flex justify-between items-center">

                    <div className="flex flex-col items-center flex-1">

                        <div
                            className={`w-12 h-12 rounded-full flex items-center justify-center text-white
                ${["Pending", "Paid", "Shipped", "Delivered"].includes(order.status)
                                    ? "bg-green-600"
                                    : "bg-gray-300"
                                }`}
                        >
                            ✓
                        </div>

                        <p className="mt-3 text-sm font-medium">
                            Pending
                        </p>

                    </div>

                    <div
                        className={`h-1 flex-1 ${["Paid", "Shipped", "Delivered"].includes(order.status)
                                ? "bg-green-600"
                                : "bg-gray-300"
                            }`}
                    />

                    <div className="flex flex-col items-center flex-1">

                        <div
                            className={`w-12 h-12 rounded-full flex items-center justify-center text-white
                ${["Paid", "Shipped", "Delivered"].includes(order.status)
                                    ? "bg-green-600"
                                    : "bg-gray-300"
                                }`}
                        >
                            ✓
                        </div>

                        <p className="mt-3 text-sm font-medium">
                            Paid
                        </p>

                    </div>

                    <div
    className={`h-1 flex-1 ${
        ["Shipped", "Delivered"].includes(order.status)
            ? "bg-green-600"
            : "bg-gray-300"
    }`}
/>

                    <div className="flex flex-col items-center flex-1">

                        <div
                            className={`w-12 h-12 rounded-full flex items-center justify-center text-white
                ${["Shipped", "Delivered"].includes(order.status)
                                    ? "bg-green-600"
                                    : "bg-gray-300"
                                }`}
                        >
                            ✓
                        </div>

                        <p className="mt-3 text-sm font-medium">
                            Shipped
                        </p>

                    </div>

                    <div
    className={`h-1 flex-1 ${
        order.status === "Delivered"
            ? "bg-green-600"
            : "bg-gray-300"
    }`}
/>

                    <div className="flex flex-col items-center flex-1">

                        <div
                            className={`w-12 h-12 rounded-full flex items-center justify-center text-white
                ${order.status === "Delivered"
                                    ? "bg-green-600"
                                    : "bg-gray-300"
                                }`}
                        >
                            ✓
                        </div>

                        <p className="mt-3 text-sm font-medium">
                            Delivered
                        </p>

                    </div>

                </div>

            </div>

            {/* Products */}

            <div className="bg-white rounded-3xl shadow-sm p-8 mt-8">

                <h2 className="text-2xl font-serif mb-6">

                    Ordered Products

                </h2>

                <div className="overflow-x-auto">

                    <table className="w-full">

                        <thead>

                            <tr className="border-b uppercase tracking-[2px] text-xs text-gray-500">

                                <th className="py-4 text-left">

                                    Product

                                </th>

                                <th>

                                    Size

                                </th>

                                <th>

                                    Qty

                                </th>

                                <th>

                                    Price

                                </th>

                                <th>

                                    Total

                                </th>

                            </tr>

                        </thead>

                        <tbody>

                            {order.items.map((item, index) => (

                                <tr
                                    key={index}
                                    className="border-b"
                                >

                                    <td className="py-5">

                                        <div className="flex items-center gap-4">

                                            <img
                                                src={item.image}
                                                alt={item.name}
                                                className="w-16 h-16 rounded-xl object-cover border"
                                            />

                                            <div>

                                                <p className="font-medium">

                                                    {item.name}

                                                </p>

                                            </div>

                                        </div>

                                    </td>

                                    <td className="text-center">

                                        {item.size || "-"}

                                    </td>

                                    <td className="text-center">

                                        {item.quantity}

                                    </td>

                                    <td className="text-center">

                                        ₹{item.price}

                                    </td>

                                    <td className="text-center font-semibold">

                                        ₹{item.price * item.quantity}

                                    </td>

                                </tr>

                            ))}

                        </tbody>

                    </table>

                </div>

            </div>

            <div className="bg-white rounded-3xl shadow-sm p-8 mt-8">

                <h2 className="text-2xl font-serif mb-6">

                    Order Summary

                </h2>

                <div className="space-y-4">

                    <div className="flex justify-between">

                        <span>

                            Total Products

                        </span>

                        <span>

                            {order.items.length}

                        </span>

                    </div>

                    <div className="flex justify-between">

                        <span>

                            Total Quantity

                        </span>

                        <span>

                            {
                                order.items.reduce(
                                    (sum, item) => sum + item.quantity,
                                    0
                                )
                            }

                        </span>

                    </div>

                    <div className="flex justify-between">

                        <span>

                            Shipping

                        </span>

                        <span>

                            FREE

                        </span>

                    </div>

                    <div className="border-t pt-5 flex justify-between">

                        <span className="text-xl font-semibold">

                            Grand Total

                        </span>

                        <span className="text-3xl font-serif">

                            ₹{order.totalAmount}

                        </span>

                    </div>

                </div>

            </div>

        </AdminLayout>

    )

}

export default AdminOrderDetails